# Generated by Django 5.2.8 on 2026-03-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0014_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='warning_count',
            field=models.IntegerField(default=0),
        ),
    ]
