# Generated by Django 5.2.8 on 2026-03-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0016_comment_moderationlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='moderationlog',
            options={'ordering': ['-timestamp']},
        ),
    ]
